version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME: admin
      - MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      -mongodb_data:/data/db

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
  
  server:
    build: 
     - context: .
     - dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - 6003:6003
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb
      - UPTASH_REDIS_URI:rediss://default:AeoRAAIjcDEyYThkODZiZTU2MGQ0ODEyODFkZjUyYWMxMzBkZGYyOXAxMA@learning-flounder-59921.upstash.io:6379
    depends_on:
      - mongodb
      - redis
    develop:
      watch:
        - path: ./package*.json
          action: rebuild
        - path: .
          target: /app
          action: sync
        
  client:
    build:
      - context: ./frontend
      - dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - 5173:5173
    env_file:
      - .env
    depends_on:
      - server
    develop:
      watch:
        - path: ./frontend/package*.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
    
volumes:
  mongodb_data:
    driver: local